// Módulos
import Head from 'next/head'
import _ from 'lodash'

// Diretórios
import { Layout } from '../../../../components/Layout'
import { Post } from '../../../../components/Post'
import { FullPageLoader } from '../../../../components/FullPageLoader'
import { getPostById } from '../../../../helpers/getPostById'

export default function PostPage({ postProps }) {
  if (_.isEmpty(postProps)) return <FullPageLoader />
  const post = JSON.parse(postProps)

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Post key={post.id} post={post} />
      </Layout>
    </div>
  )
}

export const getStaticPaths = () => {
  return {
    paths: [],
    fallback: true,
  }
}

export const getStaticProps = async context => {
  const id = context.params.postId

  const post = await getPostById(id)

  return {
    props: {
      postProps: JSON.stringify(post) || null,
    },
    revalidate: 60,
  }
}
