// Módulos
import Head from 'next/head'
import { useRouter } from 'next/router'

// Diretórios
import { Layout } from '../components/Layout'
import { VerifiedEmail } from '../components/VerifiedEmail'
import { ChangePassword } from '../components/ChangePassword'
import { PrivateRoute } from '../components/PrivateRoute'

export default function Feedback() {
  const router = useRouter()
  const routes = ['verifyEmail', 'resetPassword']

  return (
    <PrivateRoute isProtected={routes.indexOf(router.query.mode) === -1}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        {router.query.mode === 'verifyEmail' && <VerifiedEmail />}
        {router.query.mode === 'resetPassword' && <ChangePassword />}
      </Layout>
    </PrivateRoute>
  )
}
