/* eslint-disable react/no-children-prop */
// Módulos
import Head from 'next/head'
import { useForm } from 'react-hook-form'
import { yupResolver } from '@hookform/resolvers/yup'
import {
  Center,
  VStack,
  Heading,
  Button,
  InputGroup,
  InputLeftElement,
  Input,
  Text,
  useColorModeValue,
  chakra,
  FormControl,
  FormErrorMessage,
  useToast,
} from '@chakra-ui/react'
import { MdEmail } from 'react-icons/md'

// Diretórios
import { Layout } from '../components/Layout'
import { Card } from '../components/Card'
import { useAuth } from '../hooks/useAuth'
import { PrivateRoute } from '../components/PrivateRoute'
import { schema } from '../utils/schema'

export default function Recover() {
  const secondaryColor = useColorModeValue('#4A5568', '#CBD5E0')
  const { forgotPassword, currentUser } = useAuth()
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm({ resolver: yupResolver(schema.recover) })
  const toast = useToast()

  const onSubmit = async data => {
    try {
      await forgotPassword(data.email)
      toast({
        description: 'Você entrou em sua conta com sucesso.',
        status: 'success',
      })
    } catch (error) {
      toast({
        description: error.message,
        status: 'error',
      })
    }
  }

  return (
    <PrivateRoute isProtected={currentUser}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <chakra.form onSubmit={handleSubmit(onSubmit)}>
          <Center>
            <Card as={VStack} spacing={4} w={96} p={8}>
              <Heading size="lg">Recuperar senha</Heading>
              <Text fontSize="sm" textAlign="center" color={secondaryColor}>
                Insira seu endereço de e-mail para que seja possível recuperar
                sua senha
              </Text>
              <FormControl isInvalid={errors.email}>
                <InputGroup>
                  <InputLeftElement
                    pointerEvents="none"
                    children={<MdEmail color={secondaryColor} />}
                  />
                  <Input
                    variant="filled"
                    type="email"
                    placeholder="E-mail"
                    {...register('email')}
                  />
                </InputGroup>
                <FormErrorMessage>{errors.email?.message}</FormErrorMessage>
              </FormControl>
              <Button isFullWidth type="submit" variant="brand">
                Recuperar
              </Button>
            </Card>
          </Center>
        </chakra.form>
      </Layout>
    </PrivateRoute>
  )
}
